version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - 15672:15672
  arangodb:
    image: "arangodb"
    ports:
      - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=root
  couchbase:
    build:
      context: "../../"
      dockerfile: "libs/couchbase/Dockerfile"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_CLUSTER_NAME=Reddit
      - COUCHBASE_RAM=1024
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - cb_data:/opt/couchbase/var
  recommendation_app:
    build:
      context: "../../"
      dockerfile: "apps/recommendation_app/Dockerfile"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - ARANGO_DB=Reddit
      - ARANGO_USER=root
      - ARANGO_PASSWORD=root
      - ARANGO_HOST=arangodb
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=password
    depends_on:
      - "rabbitmq"
      - "arangodb"
      - "couchbase"

networks:
  default:
    name: recommendation_nw

volumes:
  cb_data:
  arangodb_data:
  arangodb_apps_data:
