version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  arangodb:
    image: "arangodb"
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=root
  couchbase:
    image: "couchbase"
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  recommendation_app:
    build:
      context: "../../"
      dockerfile: "apps/recommendation_app/Dockerfile"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - ARANGO_DB=Reddit
      - ARANGO_USER=root
      - ARANGO_PASSWORD=root
      - ARANGO_HOST=arangodb
      - COUCHBASE_HOST=localhost
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=root
    depends_on:
      - "rabbitmq"
      - "arangodb"
      - "couchbase"

networks:
  default:
    name: recommendation_nw
