apiVersion: apps/v1
kind: Deployment
metadata:
  name: netty-deployment
spec:
  selector:
    matchLabels:
      app: netty
  template:
    metadata:
      labels:
        app: netty
    spec:
      containers:
      - name: netty
        image: netty_server
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        env:
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-deployment-default-user
                key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-deployment-default-user
                key: password
        envFrom:
          - configMapRef:
              name: env-configmap
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: netty-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netty_app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  name: netty-service
spec:
  selector:
    app: netty
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-ingress
spec:
  rules:
  - host: notreddit.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: netty-service
            port: 
              number: 8080
