apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq-deployment
spec:
  image: gcr.io/reddit-31/rabbitmq:management
  replicas: 1
  persistence:
    storage: 4Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.6