version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
  arangodb:
    image: "arangodb"
    environment:
      - ARANGO_ROOT_PASSWORD=root
    ports:
      - "8529:8529"
  user_to_user_actions_app:
    build:
      context: "../../"
      dockerfile: "apps/user_to_user_actions_app/Dockerfile"
    restart: on-failure
    ports:
      - "4009:4009"
    env_file:
      - "../../.env"

    depends_on:
      - "rabbitmq"
      - "arangodb"

networks:
  default:
    name: user_actions_nw
