version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  notificiation_app:
    build:
      context: "../../"
      dockerfile: "apps/notification_app/Dockerfile"
    restart: on-failure
    env_file:
      - "../../.env"
    depends_on:
      - "rabbitmq"
networks:
  default:
    name: notification_nw
