version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  arangodb:
    image: "arangodb"
    environment:
      - ARANGO_ROOT_PASSWORD=root
    volumes:
      - ../../libs/arango/src/main/resources/shell/bash.sh:/docker-entrypoint-initdb.d/arango.sh
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ../../libs/postgres/src/main/resources/sql/CreateUsersTable.sql:/docker-entrypoint-initdb.d/1_CreateTables.sql
      - ../../libs/postgres/src/main/resources/sql/CreateUserProcedures.sql:/docker-entrypoint-initdb.d/2_CreateProcedures.sql
  user_app:
    build:
      context: "../../"
      dockerfile: "apps/user_app/Dockerfile"
    restart: on-failure
    env_file:
      - "../../.env"
    environment:
      - RABBIT_HOST=rabbitmq
      - ARANGO_DB=Reddit
      - ARANGO_USER=root
      - ARANGO_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=scaleabull
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
      - ENV_TYPE=Staging
    depends_on:
      - "rabbitmq"
      - "arangodb"
      - "postgres"

networks:
  default:
    name: user_nw
