version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  arangodb:
    image: "arangodb"
    environment:
      - ARANGO_ROOT_PASSWORD=root
    ports:
      - "1234:8529"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ../../libs/postgres/src/main/resources/sql/CreateUsersTable.sql:/docker-entrypoint-initdb.d/1_CreateTables.sql
      - ../../libs/postgres/src/main/resources/sql/CreateUserProcedures.sql:/docker-entrypoint-initdb.d/2_CreateProcedures.sql
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
  user_app:
    build:
      context: "../../"
      dockerfile: "apps/user_app/Dockerfile"
    restart: on-failure
    env_file:
      - "../../.env"
    environment:
      - RABBIT_HOST=rabbitmq
      - ARANGO_HOST=arangodb
      - ARANGO_DB=Reddit
      - ARANGO_USER=root
      - ARANGO_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
      - ENV_TYPE=Staging
      - MINIO_HOST=https://play.min.io/;
      - MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F;
      - MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - JWT_SECRET=scaleabull
      - JWT_ISSUER=org.sab

    depends_on:
      - "rabbitmq"
      - "arangodb"
      - "postgres"

networks:
  default:
    name: user_nw
