version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
  arangodb:
    image: "arangodb"
    env_file:
      - "../../.env"
    ports:
      - "8529:8529"
  couchbase:
    build:
      context: "../../"
      dockerfile: "libs/couchbase/Dockerfile"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_CLUSTER_NAME=Reddit
      - COUCHBASE_RAM=1024
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  thread_app:
    build:
      context: "../../"
      dockerfile: "apps/thread_app/Dockerfile"
    restart: on-failure
    ports:
      - "4007:4007"
    environment: 
      - ARANGO_HOST=arangodb
      - COUCHBASE_HOST=couchbase
      - RABBIT_HOST=rabbitmq
    env_file:
      - "../../.env"

    depends_on:
      - "rabbitmq"
      - "arangodb"
      - "couchbase"

networks:
  default:
    name: thread_nw
