package org.sab.thread.commands;

import com.arangodb.ArangoDB;
import com.arangodb.entity.BaseDocument;
import org.json.JSONObject;
import org.sab.arango.Arango;
import org.sab.models.Thread;
import org.sab.service.Responder;
import org.sab.validation.Attribute;
import org.sab.validation.DataType;
import org.sab.validation.Schema;
import java.util.List;

public class CreateThread extends ThreadCommand {

    @Override
    protected Schema getSchema() {
        Attribute threadName = new Attribute(THREAD_NAME, DataType.STRING, true);
        Attribute description = new Attribute(DESCRIPTION, DataType.STRING, true);
        Attribute creatorId = new Attribute(CREATOR_ID, DataType.STRING, true);
        // TODO date should be autogenerated
        Attribute dateCreated = new Attribute(DATE_CREATED, DataType.SQL_DATE, true);
        Attribute numOfFollowers = new Attribute(NUM_OF_FOLLOWERS, DataType.INT);

        return new Schema(List.of(threadName, description, creatorId, dateCreated, numOfFollowers));
    }

    private Arango arango;
    private ArangoDB arangoDB;


    @Override
    public String execute() {
        String name = body.getString(THREAD_NAME);
        String description = body.getString(DESCRIPTION);
        String creatorId = body.getString(CREATOR_ID);
        String date = body.getString(DATE_CREATED);
        long numOfFollowers = 0;

        // TODO change to constructor
        Thread thread = new Thread();


        try {
            arango = Arango.getInstance();
            arangoDB = arango.connect();

            // TODO: System.getenv("ARANGO_DB") instead of writing the DB
            if (!arango.collectionExists(arangoDB, DB_Name, THREAD_COLLECTION_NAME)) {
                arango.createCollection(arangoDB, DB_Name, THREAD_COLLECTION_NAME, false);
            }

            // TODO check creator exists and is not deleted
            BaseDocument myObject = new BaseDocument();
            myObject.setKey(name);
//            myObject.addAttribute(THREAD_NAME_DB, name);
            myObject.addAttribute(DESCRIPTION_DB, description);
            myObject.addAttribute(CREATOR_ID_DB, creatorId);
            myObject.addAttribute(DATE_CREATED_DB, date);
            myObject.addAttribute(NUM_OF_FOLLOWERS_DB, numOfFollowers);

            // TODO assign creator to be mod

            BaseDocument res = arango.createDocument(arangoDB, DB_Name, THREAD_COLLECTION_NAME, myObject);

            thread.setName(res.getKey());
            thread.setDescription((String) res.getAttribute(DESCRIPTION_DB));
            thread.setCreatorId((String) res.getAttribute(CREATOR_ID_DB));
            thread.setDateCreated((String) res.getAttribute(DATE_CREATED_DB));
            thread.setNumOfFollowers(Integer.parseInt(res.getAttribute(NUM_OF_FOLLOWERS_DB).toString()));

        } catch (Exception e) {
            return Responder.makeErrorResponse(e.getMessage(), 404).toString();
        } finally {
            arango.disconnect(arangoDB);
        }
        return Responder.makeDataResponse(thread.toJSON()).toString();
    }




    public static void main(String[] args) {
        CreateThread tc = new CreateThread();
        JSONObject request = new JSONObject("{\"body\":{\"dateCreated\":\"1998-2-9\",\"name\":\"asmakElRayes7amido\",\"creatorId\":\"sd54sdsda\",\"description\":\"agmad subreddit fl wogod\"},\"uriParams\":{},\"methodType\":\"POST\"}");
        System.out.println(tc.execute(request));
    }

}
