apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase
  labels:
    app: couchbase
spec:
  replicas: 1
  template:
    metadata:
      name: couchbase
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: gcr.io/sampleproject-31/couchbase:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
          envFrom:  
            - configMapRef:
                name: env-config
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: couchbase