apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
  labels:
    app: notification-app
spec:
  replicas: 1
  template:
    metadata:
      name: notification-app
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-app
          image: gcr.io/sampleproject-31/notification-app:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
          envFrom:  
            - configMapRef:
                name: env-config
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: notification-app