apiVersion: v1
kind: Secret
metadata:
  name: couchbase-deployment-authentication
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: v1
kind: Secret
metadata:
  name: arangodb-deployment-authentication
type: Opaque
data:
  password: cm9vdAo= # root
---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-cluster-superuser-default
type: Opaque
data:
  username: cm9vdAo= # root
  password: cm9vdAo= # root
---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-cluster-superuser-default
  namespace: cass-operator
type: Opaque
data:
  username: cm9vdAo= # root
  password: cm9vdAo= # root
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-deployment-authentication
type: Opaque
data:
  username: UTNBTTNVUTg2N1NQUVFBNDNQMkYK
  password: enVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURwo=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-deployment-authentication
type: Opaque
data:
  password: root