apiVersion: v1
kind: Secret
metadata:
  name: couchbase-deployment-authentication
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: v1
kind: Secret
metadata:
  name: arangodb-deployment-authentication
type: Opaque
data:
  password: cm9vdAo= # root
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-deployment-authentication
type: Opaque
data:
  password: root
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-deployment-authentication
type: Opaque
data:
  username: Q3AM3UQ867SPQQA43P2F
  password: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
