apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-storage-deployment
spec:
  selector:
    matchLabels:
      app: chat_storage
  template:
    metadata:
      labels:
        app: chat_storage
    spec:
      containers:
      - name: chat-storage
        image: chat_storage:alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        env:
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-deployment-default-user
                key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-deployment-default-user
                key: password
          - name: CASSANDRA_USERNAME
            valueFrom:
              secretKeyRef:
                name: cassandra-cluster-superuser-default
                key: username
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cassandra-cluster-superuser-default
                key: password
        envFrom:
          - configMapRef:
              name: env-configmap
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-storage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-storage-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60