apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  selector:
    matchLabels:
      app: user_app
  template:
    metadata:
      labels:
        app: user_app
    spec:
      containers:
        - name: user-app
          image: user_app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 4008
          env:
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-deployment-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-deployment-default-user
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-deployment-authentication
                  key: password
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-deployment-authentication
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-deployment-authentication
                  key: password
          envFrom:
            - configMapRef:
                name: env-configmap
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
