version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  arangodb:
    image: "arangodb"
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=koko
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://arangodb:8529" ]
      interval: 10s
      timeout: 10s
      retries: 10
  search_app:
    build:
      context: "../../"
      dockerfile: "apps/search_app/Dockerfile"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - ARANGO_DB=_system
      - ARANGO_USER=root
      - ARANGO_PASSWORD=koko
      - ARANGO_HOST=arangodb
    depends_on:
      - "arangodb"
      - "rabbitmq"


networks:
  default:
    name: search_nw
