version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
  # cassandra:
  #     image: "cassandra"
  chat_server:
    build:
      context: "../../"
      dockerfile: "apps/chat_app/chat_server/Dockerfile"
    env_file:
      - ./../../.env
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - "5000:5000"
    depends_on:
      - "rabbitmq"
  chat_storage:
    build:
      context: "../../"
      dockerfile: "apps/chat_app/chat_storage/Dockerfile"
    restart: on-failure
    ports:
      - "4001:4001"
    environment:
      - RABBIT_HOST=rabbitmq
      - CASSANDRA_NODE=192.168.43.33
      - CASSANDRA_PORT=9042
      - KEYSPACE_NAME=chat_app
      - REPLICATION_STRATEGY=SimpleStrategy
      - REPLICATION_FACTOR=2
    depends_on:
      #   - "cassandra"
      - "rabbitmq"

networks:
  default:
    name: chat_nw
